/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.validation;

import java.util.HashSet;
import java.util.Set;
import org.eclipse.emf.common.util.EList;
import org.eclipse.xtext.validation.Check;
import org.xtext.example.mydsl.myDsl.MathExp;
import org.xtext.example.mydsl.myDsl.MathExpression;
import org.xtext.example.mydsl.myDsl.MyDslPackage;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MyDslValidator extends AbstractMyDslValidator {
  @Check
  public void checkNoRepeatedGlobalVarDeclaration(final MathExpression mathExpression) {
    final Set<String> declaredVariables = new HashSet<String>();
    EList<MathExp> _expressions = mathExpression.getExpressions();
    for (final MathExp mathExp : _expressions) {
      {
        final String variableName = mathExp.getName();
        boolean _contains = declaredVariables.contains(variableName);
        if (_contains) {
          this.error(("Repeated global variable declaration: " + variableName), 
            MyDslPackage.Literals.MATH_EXP__NAME);
        } else {
          declaredVariables.add(variableName);
        }
      }
    }
  }
}
