/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Let</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Let#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Let#getBind <em>Bind</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Let#getVarName <em>Var Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLet()
 * @model
 * @generated
 */
public interface Let extends Expression
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLet_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Let#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Bind</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bind</em>' containment reference.
   * @see #setBind(Expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLet_Bind()
   * @model containment="true"
   * @generated
   */
  Expression getBind();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Let#getBind <em>Bind</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bind</em>' containment reference.
   * @see #getBind()
   * @generated
   */
  void setBind(Expression value);

  /**
   * Returns the value of the '<em><b>Var Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Name</em>' containment reference.
   * @see #setVarName(Expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLet_VarName()
   * @model containment="true"
   * @generated
   */
  Expression getVarName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Let#getVarName <em>Var Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Name</em>' containment reference.
   * @see #getVarName()
   * @generated
   */
  void setVarName(Expression value);

} // Let
