/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Extension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.xtext.example.mydsl.myDsl.MathExp;

@ExtendWith(InjectionExtension.class)
@InjectWith(MyDslInjectorProvider.class)
@SuppressWarnings("all")
public class MathExampleTest {
  @Inject
  @Extension
  private ParseHelper<MathExp> _parseHelper;

  @Test
  public void mathematicalOperations() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field compute is undefined for the type MathExp"
      + "\nget cannot be resolved"
      + "\nget cannot be resolved"
      + "\nget cannot be resolved"
      + "\nget cannot be resolved"
      + "\nget cannot be resolved"
      + "\nget cannot be resolved");
  }

  @Test
  public void letAndScope() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field compute is undefined for the type MathExp"
      + "\nget cannot be resolved"
      + "\nget cannot be resolved"
      + "\nget cannot be resolved"
      + "\nget cannot be resolved"
      + "\nget cannot be resolved");
  }

  @Test
  public void evilExample() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field compute is undefined for the type MathExp"
      + "\nget cannot be resolved"
      + "\nget cannot be resolved"
      + "\nget cannot be resolved"
      + "\nget cannot be resolved"
      + "\nget cannot be resolved");
  }
}
